version: '2'
networks:
  app-network:
services:
  app:
    image: conda/miniconda3
    volumes:
      - ./:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 5000:5000
    networks:
      - app-network

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - app-network
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1